name: KitUI
author: Infernus101
api: [3.0.0-ALPHA12]
main: Infernus101\KitUI\Main
version: 1.2.2
permissions: # kit permissions - kit.<kit name>
 kit.command:
  description: kit command!
  default: true
 kit.sign:
   description: kit sign!
   default: false
commands:
  kit:
    description: Kit UI!
